spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@database-1.ctmkmo062uiz.ap-northeast-2.rds.amazonaws.com:1521:orcl"
    username: ${ORACLE_RDS_USERNAME}
    password: ${ORACLE_RDS_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 60000
      validation-timeout: 5000
      test-on-borrow: true
      test-while-idle: true
      validation-query: "SELECT 1 FROM DUAL"

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      mvc:
        view:
          suffix: .html


jwt:
  # 32글자 이상 인코딩된 문자열: oauthserversecretaccesstokenoauthserversecretaccesstokenoauthserversecretaccesstoken
  secret: ${JWT_SECRET}
  access-expiration: 30 #분단위
  refresh-expiration: 20160 # 리프레시 토큰 만료: 14일 (14*24*60 = 20160분)

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://teamcodegears.github.io/michki-frontend/oauth/google/redirect
#    redirect-uri: http://localhost:8080/oauth/google/redirect