name: CI (skip tests)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul

    defaults:
      run:
        working-directory: michiki

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (skip tests)
        run: ./gradlew clean build -x test --no-daemon -Duser.timezone=Asia/Seoul
        # 필요시 더 빠르게: ./gradlew clean bootJar -x test --no-daemon

      - name: Show build outputs
        run: ls -al build/libs

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jars-${{ github.sha }}
          path: build/libs/*.jar